# Connecting to APIs

### What is an API?

**A**pplication **P**rogramming **I**nterface:

API is how computers communicate. It's a connection point, typically over the internet, that allows two computers to interact. For our purposes, it provides a safe and legal way to access large amounts of structured data from the web, whether owned by private companies, governments, or public organizations. 

APIs are used to send and receive data, and they define what data can be exchanged and the commands/syntax used.

### Why use APIs?

Many organizations rely on the web as a key source of data:
- Agricultural commodity traders want real-time access to weather data via web APIs as weather conditions affect the supply of the commodity, and therefore the price.
- Reliability engineers at mine sites want to access the data streamed off ore processing machinery then stored in “the cloud”
- Market research firms use the Twitter APIs to uncover important consumer trends.

### How does it work?

![from g2.com](https://learn.g2.com/hs-fs/hubfs/G2CM_FI167_Learn_Article_Images_%5BAPI%5D_Infographic_V1a.png)

#### Steps:
1.	Request:
    -	A client (You) sends a request to an API server through the internet. 
    -	This request is in a form of a URL with specific parameters, indicating the desired action. In some instances, it may include authentication credentials to verify the client's identity.
2.	Process:
    -	The API server receives the request and processes it.  It interprets the request, determines the appropriate action, and fetches the necessary data from its database or other sources.
3.	Response:
    -	The API server sends a response back to the client. The response typically contains the requested data in a specific format, such as JSON or XML.  It may also include additional information like error codes or success messages.


**👉** We do need to be aware of __[HTTP status codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)__ provided by the API that will inform us if our requests:

|Code|Reason|
|---|-----|
|200|Succeed|
|400 - 599|Failed|
|404|Does not exist|

# APIs UK Crime Street Data

## Getting Police Data

Let's request data from this API: https://data.police.uk/docs/

Take a few moments to read through some of the information on this site and figure out:

* Where this API gets its data from (and whether it's a reputable source)
* How we can access the documentation that tells us how the API works
* Whether the API is free

<details><summary>Which endpoint looks promising to help us answer our challenge of finding out about the prevalence of different types of crimes around the UK?</summary>

The ‘street level crimes’ endpoint looks promising: https://data.police.uk/docs/method/crime-street/
</details>

Let's start by importing the `requests` library, which we'll be using to make API requests.

In [68]:
import requests
import pandas as pd
from pprint import pprint

Let's make a request to the police API and view the resulting JSON. The first thing we do is make a GET request. This is really simple!

In [39]:
crime_request = requests.get('https://data.police.uk/api/crimes-street/all-crime?date=2024-01&lat=52.629729&lng=-1.131592')
crime_request

The thing we get back from a GET request is a `request` object.

In [40]:
type(crime_request)

requests.models.Response

This is an object that has a few different bits of information bundled up inside it, all of which have been sent back to us by the servers.

The thing we're interested in, is accessing the JSON (or dictionary) data that's returned by the API. We do this in a single step:

In [41]:
crime_request.json()

[{'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.616723',
   'street': {'id': 1738898, 'name': 'On or near Adderley Road'},
   'longitude': '-1.122614'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208758,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.631624',
   'street': {'id': 1738751, 'name': 'On or near Station Street'},
   'longitude': '-1.125641'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208627,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.636041',
   'street': {'id': 1738351, 'name': 'On or near East Gates'},
   'longitude': '-1.133444'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208664,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.631121',
   'street': {'id': 1739564, 'name': 'On or near Dronfield Street'},
   'longitude': '-1.108837'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116209100,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.621217',
   'street': {'id': 1737965, 'name': 'On or near Pavilion Close'},
   'longitude': '-1.138404'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208682,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.634169',
   'street': {'id': 1738654, 'name': 'On or near Colton Street'},
   'longitude': '-1.128191'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116209079,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.637041',
   'street': {'id': 1738379, 'name': 'On or near Parking Area'},
   'longitude': '-1.131222'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208589,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.628462',
   'street': {'id': 1738792, 'name': 'On or near De Montfort Square'},
   'longitude': '-1.126029'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208978,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.628462',
   'street': {'id': 1738792, 'name': 'On or near De Montfort Square'},
   'longitude': '-1.126029'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208602,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.636041',
   'street': {'id': 1738351, 'name': 'On or near East Gates'},
   'longitude': '-1.133444'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208899,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.636041',
   'street': {'id': 1738351, 'name': 'On or near East Gates'},
   'longitude': '-1.133444'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208603,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.625551',
   'street': {'id': 1737260, 'name': 'On or near Petrol Station'},
   'longitude': '-1.152191'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208871,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.635555',
   'street': {'id': 1738528, 'name': 'On or near Yeoman Lane'},
   'longitude': '-1.129626'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208896,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.632052',
   'street': {'id': 1737636, 'name': 'On or near Supermarket'},
   'longitude': '-1.146096'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208820,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.639872',
   'street': {'id': 1739117, 'name': 'On or near Parking Area'},
   'longitude': '-1.118959'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208691,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.627703',
   'street': {'id': 1738945, 'name': 'On or near The Oval'},
   'longitude': '-1.123030'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208693,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.636041',
   'street': {'id': 1738351, 'name': 'On or near East Gates'},
   'longitude': '-1.133444'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208694,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.632052',
   'street': {'id': 1737636, 'name': 'On or near Supermarket'},
   'longitude': '-1.146096'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208973,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.627703',
   'street': {'id': 1738945, 'name': 'On or near The Oval'},
   'longitude': '-1.123030'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208698,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.635528',
   'street': {'id': 1738700, 'name': 'On or near Theatre/concert Hall'},
   'longitude': '-1.127553'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208704,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.622852',
   'street': {'id': 1737331, 'name': 'On or near Bisley Street'},
   'longitude': '-1.150707'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208554,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.642883',
   'street': {'id': 1738841, 'name': 'On or near Calgary Road'},
   'longitude': '-1.124914'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208606,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.635528',
   'street': {'id': 1738700, 'name': 'On or near Theatre/concert Hall'},
   'longitude': '-1.127553'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208706,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.626768',
   'street': {'id': 1738882,
    'name': 'On or near Further/higher Educational Building'},
   'longitude': '-1.123078'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208610,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.637041',
   'street': {'id': 1738379, 'name': 'On or near Parking Area'},
   'longitude': '-1.131222'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208709,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.630623',
   'street': {'id': 1739386, 'name': 'On or near Twycross Street'},
   'longitude': '-1.113087'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208713,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.630803',
   'street': {'id': 1737674, 'name': 'On or near Bede Street'},
   'longitude': '-1.144983'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208718,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.635078',
   'street': {'id': 1737968, 'name': 'On or near St Nicholas Place'},
   'longitude': '-1.139462'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208618,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.633317',
   'street': {'id': 1738721, 'name': 'On or near Church Street'},
   'longitude': '-1.127203'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208720,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.632052',
   'street': {'id': 1737636, 'name': 'On or near Supermarket'},
   'longitude': '-1.146096'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208725,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.634409',
   'street': {'id': 1738338, 'name': 'On or near Shopping Area'},
   'longitude': '-1.133652'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208726,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.636041',
   'street': {'id': 1738351, 'name': 'On or near East Gates'},
   'longitude': '-1.133444'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208747,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.628349',
   'street': {'id': 1739483, 'name': 'On or near Roslyn Street'},
   'longitude': '-1.110769'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208749,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.636041',
   'street': {'id': 1738351, 'name': 'On or near East Gates'},
   'longitude': '-1.133444'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208981,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.638358',
   'street': {'id': 1738578, 'name': 'On or near Parking Area'},
   'longitude': '-1.129437'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208646,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.636041',
   'street': {'id': 1738351, 'name': 'On or near East Gates'},
   'longitude': '-1.133444'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208648,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.632805',
   'street': {'id': 1738842, 'name': 'On or near Campbell Street'},
   'longitude': '-1.124819'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208998,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.636041',
   'street': {'id': 1738351, 'name': 'On or near East Gates'},
   'longitude': '-1.133444'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208999,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.618429',
   'street': {'id': 1739131, 'name': 'On or near Edward Road'},
   'longitude': '-1.118666'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116209004,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.627381',
   'street': {'id': 1738616, 'name': 'On or near Regent Road'},
   'longitude': '-1.126952'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116209017,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.628313',
   'street': {'id': 1738497, 'name': 'On or near Turner Street'},
   'longitude': '-1.131351'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116209020,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.628313',
   'street': {'id': 1738497, 'name': 'On or near Turner Street'},
   'longitude': '-1.131351'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116209023,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.627903',
   'street': {'id': 1739501, 'name': 'On or near Conifer Close'},
   'longitude': '-1.110084'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116209025,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.627379',
   'street': {'id': 1738753, 'name': 'On or near De Montfort Street'},
   'longitude': '-1.125445'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208763,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.634503',
   'street': {'id': 1737385, 'name': 'On or near Kate Street'},
   'longitude': '-1.149403'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208619,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.635486',
   'street': {'id': 1738632, 'name': 'On or near Yeoman Street'},
   'longitude': '-1.128741'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208652,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.625551',
   'street': {'id': 1737260, 'name': 'On or near Petrol Station'},
   'longitude': '-1.152191'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208653,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.636041',
   'street': {'id': 1738351, 'name': 'On or near East Gates'},
   'longitude': '-1.133444'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208654,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.630693',
   'street': {'id': 1738552, 'name': 'On or near Wellington Street'},
   'longitude': '-1.129885'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208655,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.640498',
   'street': {'id': 1737983, 'name': "On or near St Margaret's Street"},
   'longitude': '-1.136799'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208776,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.632052',
   'street': {'id': 1737636, 'name': 'On or near Supermarket'},
   'longitude': '-1.146096'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208620,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.625820',
   'street': {'id': 1737867, 'name': 'On or near Windermere Street'},
   'longitude': '-1.140899'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208784,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.627703',
   'street': {'id': 1738945, 'name': 'On or near The Oval'},
   'longitude': '-1.123030'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208788,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.632052',
   'street': {'id': 1737636, 'name': 'On or near Supermarket'},
   'longitude': '-1.146096'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208792,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.636041',
   'street': {'id': 1738351, 'name': 'On or near East Gates'},
   'longitude': '-1.133444'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208793,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.627534',
   'street': {'id': 1738536, 'name': 'On or near Newtown Street'},
   'longitude': '-1.130553'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208658,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.625551',
   'street': {'id': 1737260, 'name': 'On or near Petrol Station'},
   'longitude': '-1.152191'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208797,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.632534',
   'street': {'id': 1738358, 'name': 'On or near Market Street'},
   'longitude': '-1.133232'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208798,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.632052',
   'street': {'id': 1737636, 'name': 'On or near Supermarket'},
   'longitude': '-1.146096'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208803,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',

Let's create a variable that contains the JSON only.

In [42]:
crime_json = crime_request.json()
crime_json

[{'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.616723',
   'street': {'id': 1738898, 'name': 'On or near Adderley Road'},
   'longitude': '-1.122614'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208758,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.631624',
   'street': {'id': 1738751, 'name': 'On or near Station Street'},
   'longitude': '-1.125641'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208627,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.636041',
   'street': {'id': 1738351, 'name': 'On or near East Gates'},
   'longitude': '-1.133444'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208664,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.631121',
   'street': {'id': 1739564, 'name': 'On or near Dronfield Street'},
   'longitude': '-1.108837'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116209100,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.621217',
   'street': {'id': 1737965, 'name': 'On or near Pavilion Close'},
   'longitude': '-1.138404'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208682,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.634169',
   'street': {'id': 1738654, 'name': 'On or near Colton Street'},
   'longitude': '-1.128191'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116209079,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.637041',
   'street': {'id': 1738379, 'name': 'On or near Parking Area'},
   'longitude': '-1.131222'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208589,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.628462',
   'street': {'id': 1738792, 'name': 'On or near De Montfort Square'},
   'longitude': '-1.126029'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208978,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.628462',
   'street': {'id': 1738792, 'name': 'On or near De Montfort Square'},
   'longitude': '-1.126029'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208602,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.636041',
   'street': {'id': 1738351, 'name': 'On or near East Gates'},
   'longitude': '-1.133444'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208899,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.636041',
   'street': {'id': 1738351, 'name': 'On or near East Gates'},
   'longitude': '-1.133444'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208603,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.625551',
   'street': {'id': 1737260, 'name': 'On or near Petrol Station'},
   'longitude': '-1.152191'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208871,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.635555',
   'street': {'id': 1738528, 'name': 'On or near Yeoman Lane'},
   'longitude': '-1.129626'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208896,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.632052',
   'street': {'id': 1737636, 'name': 'On or near Supermarket'},
   'longitude': '-1.146096'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208820,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.639872',
   'street': {'id': 1739117, 'name': 'On or near Parking Area'},
   'longitude': '-1.118959'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208691,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.627703',
   'street': {'id': 1738945, 'name': 'On or near The Oval'},
   'longitude': '-1.123030'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208693,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.636041',
   'street': {'id': 1738351, 'name': 'On or near East Gates'},
   'longitude': '-1.133444'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208694,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.632052',
   'street': {'id': 1737636, 'name': 'On or near Supermarket'},
   'longitude': '-1.146096'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208973,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.627703',
   'street': {'id': 1738945, 'name': 'On or near The Oval'},
   'longitude': '-1.123030'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208698,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.635528',
   'street': {'id': 1738700, 'name': 'On or near Theatre/concert Hall'},
   'longitude': '-1.127553'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208704,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.622852',
   'street': {'id': 1737331, 'name': 'On or near Bisley Street'},
   'longitude': '-1.150707'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208554,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.642883',
   'street': {'id': 1738841, 'name': 'On or near Calgary Road'},
   'longitude': '-1.124914'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208606,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.635528',
   'street': {'id': 1738700, 'name': 'On or near Theatre/concert Hall'},
   'longitude': '-1.127553'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208706,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.626768',
   'street': {'id': 1738882,
    'name': 'On or near Further/higher Educational Building'},
   'longitude': '-1.123078'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208610,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.637041',
   'street': {'id': 1738379, 'name': 'On or near Parking Area'},
   'longitude': '-1.131222'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208709,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.630623',
   'street': {'id': 1739386, 'name': 'On or near Twycross Street'},
   'longitude': '-1.113087'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208713,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.630803',
   'street': {'id': 1737674, 'name': 'On or near Bede Street'},
   'longitude': '-1.144983'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208718,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.635078',
   'street': {'id': 1737968, 'name': 'On or near St Nicholas Place'},
   'longitude': '-1.139462'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208618,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.633317',
   'street': {'id': 1738721, 'name': 'On or near Church Street'},
   'longitude': '-1.127203'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208720,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.632052',
   'street': {'id': 1737636, 'name': 'On or near Supermarket'},
   'longitude': '-1.146096'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208725,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.634409',
   'street': {'id': 1738338, 'name': 'On or near Shopping Area'},
   'longitude': '-1.133652'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208726,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.636041',
   'street': {'id': 1738351, 'name': 'On or near East Gates'},
   'longitude': '-1.133444'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208747,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.628349',
   'street': {'id': 1739483, 'name': 'On or near Roslyn Street'},
   'longitude': '-1.110769'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208749,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.636041',
   'street': {'id': 1738351, 'name': 'On or near East Gates'},
   'longitude': '-1.133444'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208981,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.638358',
   'street': {'id': 1738578, 'name': 'On or near Parking Area'},
   'longitude': '-1.129437'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208646,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.636041',
   'street': {'id': 1738351, 'name': 'On or near East Gates'},
   'longitude': '-1.133444'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208648,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.632805',
   'street': {'id': 1738842, 'name': 'On or near Campbell Street'},
   'longitude': '-1.124819'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208998,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.636041',
   'street': {'id': 1738351, 'name': 'On or near East Gates'},
   'longitude': '-1.133444'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208999,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.618429',
   'street': {'id': 1739131, 'name': 'On or near Edward Road'},
   'longitude': '-1.118666'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116209004,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.627381',
   'street': {'id': 1738616, 'name': 'On or near Regent Road'},
   'longitude': '-1.126952'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116209017,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.628313',
   'street': {'id': 1738497, 'name': 'On or near Turner Street'},
   'longitude': '-1.131351'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116209020,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.628313',
   'street': {'id': 1738497, 'name': 'On or near Turner Street'},
   'longitude': '-1.131351'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116209023,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.627903',
   'street': {'id': 1739501, 'name': 'On or near Conifer Close'},
   'longitude': '-1.110084'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116209025,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.627379',
   'street': {'id': 1738753, 'name': 'On or near De Montfort Street'},
   'longitude': '-1.125445'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208763,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.634503',
   'street': {'id': 1737385, 'name': 'On or near Kate Street'},
   'longitude': '-1.149403'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208619,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.635486',
   'street': {'id': 1738632, 'name': 'On or near Yeoman Street'},
   'longitude': '-1.128741'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208652,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.625551',
   'street': {'id': 1737260, 'name': 'On or near Petrol Station'},
   'longitude': '-1.152191'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208653,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.636041',
   'street': {'id': 1738351, 'name': 'On or near East Gates'},
   'longitude': '-1.133444'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208654,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.630693',
   'street': {'id': 1738552, 'name': 'On or near Wellington Street'},
   'longitude': '-1.129885'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208655,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.640498',
   'street': {'id': 1737983, 'name': "On or near St Margaret's Street"},
   'longitude': '-1.136799'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208776,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.632052',
   'street': {'id': 1737636, 'name': 'On or near Supermarket'},
   'longitude': '-1.146096'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208620,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.625820',
   'street': {'id': 1737867, 'name': 'On or near Windermere Street'},
   'longitude': '-1.140899'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208784,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.627703',
   'street': {'id': 1738945, 'name': 'On or near The Oval'},
   'longitude': '-1.123030'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208788,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.632052',
   'street': {'id': 1737636, 'name': 'On or near Supermarket'},
   'longitude': '-1.146096'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208792,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.636041',
   'street': {'id': 1738351, 'name': 'On or near East Gates'},
   'longitude': '-1.133444'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208793,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.627534',
   'street': {'id': 1738536, 'name': 'On or near Newtown Street'},
   'longitude': '-1.130553'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208658,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.625551',
   'street': {'id': 1737260, 'name': 'On or near Petrol Station'},
   'longitude': '-1.152191'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208797,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.632534',
   'street': {'id': 1738358, 'name': 'On or near Market Street'},
   'longitude': '-1.133232'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208798,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',
  'location': {'latitude': '52.632052',
   'street': {'id': 1737636, 'name': 'On or near Supermarket'},
   'longitude': '-1.146096'},
  'context': '',
  'outcome_status': None,
  'persistent_id': '',
  'id': 116208803,
  'location_subtype': '',
  'month': '2024-01'},
 {'category': 'anti-social-behaviour',
  'location_type': 'Force',

Let's check its type: it's a dictionary.

In [43]:
type(crime_json[0])

dict

Now we can use our dictionary and list-indexing skills to access information inside the JSON.

In [44]:
first_crime = crime_json[0]
first_crime

{'category': 'anti-social-behaviour',
 'location_type': 'Force',
 'location': {'latitude': '52.616723',
  'street': {'id': 1738898, 'name': 'On or near Adderley Road'},
  'longitude': '-1.122614'},
 'context': '',
 'outcome_status': None,
 'persistent_id': '',
 'id': 116208758,
 'location_subtype': '',
 'month': '2024-01'}

In [45]:
first_crime["category"]

'anti-social-behaviour'

In [46]:
first_crime["location"]

{'latitude': '52.616723',
 'street': {'id': 1738898, 'name': 'On or near Adderley Road'},
 'longitude': '-1.122614'}

In [47]:
first_crime["location"]["street"]

{'id': 1738898, 'name': 'On or near Adderley Road'}

In [134]:
pd.DataFrame(crime_json).head()

,category,location_type,location,context,outcome_status,persistent_id,id,location_subtype,month
0,anti-social-behaviour,Force,"{'latitude': '52.616723', 'street': {'id': 173...",,None,,116208758,,2024-01
1,anti-social-behaviour,Force,"{'latitude': '52.631624', 'street': {'id': 173...",,None,,116208627,,2024-01
2,anti-social-behaviour,Force,"{'latitude': '52.636041', 'street': {'id': 173...",,None,,116208664,,2024-01
3,anti-social-behaviour,Force,"{'latitude': '52.631121', 'street': {'id': 173...",,None,,116209100,,2024-01
4,anti-social-behaviour,Force,"{'latitude': '52.621217', 'street': {'id': 173...",,None,,116208682,,2024-01

In [133]:
pd.json_normalize(crime_json).head()

,category,location_type,context,outcome_status,persistent_id,id,location_subtype,month,location.latitude,location.street.id,location.street.name,location.longitude,outcome_status.category,outcome_status.date
0,anti-social-behaviour,Force,,NaN,,116208758,,2024-01,52.616723,1738898,On or near Adderley Road,-1.122614,NaN,NaN
1,anti-social-behaviour,Force,,NaN,,116208627,,2024-01,52.631624,1738751,On or near Station Street,-1.125641,NaN,NaN
2,anti-social-behaviour,Force,,NaN,,116208664,,2024-01,52.636041,1738351,On or near East Gates,-1.133444,NaN,NaN
3,anti-social-behaviour,Force,,NaN,,116209100,,2024-01,52.631121,1739564,On or near Dronfield Street,-1.108837,NaN,NaN
4,anti-social-behaviour,Force,,NaN,,116208682,,2024-01,52.621217,1737965,On or near Pavilion Close,-1.138404,NaN,NaN

# Now You Try
    
Let’s find out about crimes in different parts of the UK.

We'll use the ‘street level crimes’ endpoint again: https://data.police.uk/docs/method/crime-street/

* Can you make a request to this URL and find out how many crimes were committed in the immediate area around **Piccadilly Circus Station** in London in January 2023?
    
The steps you need to follow are:
* Find the location on Google Maps, to get the longitude and latitude
* Use this information to build your API request

Now, do the same to find the crimes around the **Buckingham Palace** in **July 2024**.

In [52]:
# Piccadilly Circus
lat = 51.508624722468454
lon = -0.14708795945249462
date='2024-01'

police_url = f'https://data.police.uk/api/crimes-street/all-crime?date={date}&lat={str(lat)}&lng={str(lon)}'
police_json = requests.get(police_url).json()

print(len(police_json))

6372

In [53]:
# Buckingham Palace
lat = 51.501924975588814
lon = -0.1404308807450789
date='2024-01'

police_url = f'https://data.police.uk/api/crimes-street/all-crime?date={date}&lat={str(lat)}&lng={str(lon)}'
police_json = requests.get(police_url).json()

print(len(police_json))

5493

---
<img src="https://www.data.gov.bh/assets/theme_image/logo-en.png" alt="Bahrain Open Source" width="500"/>

### __[Bahrain Open Portal - Import 2026](https://www.data.gov.bh/explore/dataset/import-2026/api/?disjunctive.month)__

Access the link and go through the documentation. Notice that you have the option to customize your URL to include the information your require.

#### ☕ Get coffee import transactions to Bahrain for the year 2026.

__For this example let's select the following:__
- __SELECT:__ month, commodity_no, commodity, country_name, un_code, import_weight_kg, import_value_bd
- __WHERE:__ commodity LIKE "Coffee"
- __LIMIT:__ 100   _(this is because we have a limit of 100 records per request)_

Click on **Submit** and Copy the url generated *(Note: If you click on the url, you will be able to view the sample data in JSON format)*

In [54]:
# The url generated
url_import_bh = 'https://www.data.gov.bh/api/explore/v2.1/catalog/datasets/import-2026/records?select=month%2C%20commodity_no%2C%20commodity%2C%20country_name%2C%20un_code%2C%20import_weight_kg%2C%20import_value_bd&where=commodity%20LIKE%20%22Coffee%22&limit=100'

In [55]:
# Send a request for the data
coffee_import_bh = requests.get(url_import_bh)

# print request code status 
print(coffee_import_bh.status_code)

200

In [56]:
# Get the data - notice that we have a dictionary with two keys - 'total_count' and 'results'
# 'total_count' is the total records in the query
# 'results' is a list of the first 100 records
coffee_2026_data = coffee_import_bh.json()
coffee_2026_data.keys()

dict_keys(['total_count', 'results'])

In [57]:
# Get total records in the query
coffee_2026_data['total_count']

611

__How do we get the remaining records?__

We use '__offset__'! - Offset skips certain number of records. If our limit is 100 and offset is 100 then it the api (query) will skip the first 100 records then gets the next 100. Lets go back to the open portal and try adding 100 to **offset**, then notice the end of the string.

```python
'''https://www.data.gov.bh/api/explore/v2.1/catalog/datasets/import-2026/records?select=month%2C%20commodity_no%2C%20commodity%2C%20country_name%2C%20un_code%2C%20import_weight_kg%2C%20import_value_bd&
where=commodity%20LIKE%20%22Coffee%22&
limit=100&
offset=100'''
```

#### __🧮 Now lets do some simple math + base python and get the whole data then added to a DataFrame! 💪__

In [58]:
list_coffee = []
# Add the first API request we did that contains the first 100 records
list_coffee.extend(coffee_2026_data['results'])
list_coffee[:5]

[{'month': '02 February',
  'commodity_no': '09019000',
  'commodity': 'OTHER COFFEE',
  'country_name': 'INDIA',
  'un_code': 'IN',
  'import_weight_kg': 216.0,
  'import_value_bd': 498.1946788},
 {'month': '02 February',
  'commodity_no': '21011220',
  'commodity': 'COFFEE PASTE',
  'country_name': 'SPAIN',
  'un_code': 'ES',
  'import_weight_kg': 195.0,
  'import_value_bd': 358.7720625},
 {'month': '01 January',
  'commodity_no': '09019000',
  'commodity': 'OTHER COFFEE',
  'country_name': 'FRANCE',
  'un_code': 'FR',
  'import_weight_kg': 15.048,
  'import_value_bd': 478.47},
 {'month': '01 January',
  'commodity_no': '21011220',
  'commodity': 'COFFEE PASTE',
  'country_name': 'UNITED KINGDOM',
  'un_code': 'GB',
  'import_weight_kg': 7.725,
  'import_value_bd': 108.064},
 {'month': '01 January',
  'commodity_no': '21011220',
  'commodity': 'COFFEE PASTE',
  'country_name': 'INDONESIA',
  'un_code': 'ID',
  'import_weight_kg': 188.25,
  'import_value_bd': 360.822}]

In [59]:
# Get the total number of records
number_records = coffee_2026_data['total_count']
number_records

611

In [60]:
# number_records//100+1 ==> wil give us the number of times we need to loop: Total number of records // number of records per request
# number_records%100 will check if the records is divisible by 100, if it is not then it will 1 else 0
extra_loop = 1 if number_records%100 !=0 else 0
for i in range(1,number_records//100+extra_loop):
    # Request for the next 100 records
    
    url_coffee = f'https://www.data.gov.bh/api/explore/v2.1/catalog/datasets/import-2026/records?select=month%2C%20commodity_no%2C%20commodity%2C%20country_name%2C%20un_code%2C%20import_weight_kg%2C%20import_value_bd&where=commodity%20LIKE%20%22Coffee%22&limit=100&offset={i*100}'
    coffee_import_bh = requests.get(url_coffee)
    # Add the records to list_coffee
    list_coffee.extend(coffee_import_bh.json()['results'])

In [61]:
len(list_coffee)

611

In [113]:
coffee_df = pd.DataFrame(list_coffee)
coffee_df.head()

,month,commodity_no,commodity,country_name,un_code,import_weight_kg,import_value_bd
0,02 February,09019000,OTHER COFFEE,INDIA,IN,216.000,498.194679
1,02 February,21011220,COFFEE PASTE,SPAIN,ES,195.000,358.772063
2,01 January,09019000,OTHER COFFEE,FRANCE,FR,15.048,478.470000
3,01 January,21011220,COFFEE PASTE,UNITED KINGDOM,GB,7.725,108.064000
4,01 January,21011220,COFFEE PASTE,INDONESIA,ID,188.250,360.822000

#### 🍵 Now, explore the tea import transactions to Bahrain for the year 2025.

In [128]:
url_import = 'https://www.data.gov.bh/api/explore/v2.1/catalog/datasets/import-1-2025/records?select=month%2C%20commodity_no%2C%20commodity%2C%20country_name%2C%20un_code%2C%20import_weight_kg%2C%20import_value_bd&where=commodity%20LIKE%20%22Coffee%22%20OR%20commodity%20LIKE%20%22Tea%22&limit=100'

In [129]:
# Send a request for the data
import_bh = requests.get(url_import)

# print request code status 
print(import_bh.status_code)

200

In [130]:
number_records = import_bh.json()['total_count']
number_records

2580

In [131]:
# number_records//100+1 ==> wil give us the number of times we need to loop: Total number of records // number of records per request
# number_records%100 will check if the records is divisible by 100, if it is not then it will 1 else 0
extra_loop = 1 if number_records%100 !=0 else 0
list_tea_coffee = []
for i in range(1,number_records//100+extra_loop):
    # Request for the next 100 records
    
    url_tea = f'{url_import}&offset={i*100}'
    import_bh = requests.get(url_tea)
    # Add the records to list_tea
    list_tea_coffee.extend(import_bh.json()['results'])

In [132]:
tea_df = pd.DataFrame(list_tea_coffee)
tea_df.head()

,month,commodity_no,commodity,country_name,un_code,import_weight_kg,import_value_bd
0,12 December,85167100,COFFEE OR TEA MAKERS,UNITED KINGDOM,GB,0.100,309.689
1,12 December,85167100,COFFEE OR TEA MAKERS,HUNGARY,HU,237.000,4734.416
2,12 December,85167100,COFFEE OR TEA MAKERS,ITALY,IT,719.750,6753.418
3,12 December,85167100,COFFEE OR TEA MAKERS,PORTUGAL,PT,29.723,1078.079
4,12 December,85167100,COFFEE OR TEA MAKERS,QATAR,QA,13.000,347.928

__Find the following for both Coffee and Tea related Imports (include visualizations):__
- Top 10 importing countries by weight or value

In [117]:
# Coffee

In [ ]:
# Tea

- Top 5 commodities imported

In [118]:
# Top 5 Tea commodities imported

In [ ]:
# Top 5 Coffee commodities imported

- Months of the year with the highest import volumes

__________

## __API Exercise__

### __[OMDB API :](https://www.omdbapi.com/)__
The OMDb API is a RESTful web service to obtain movie information, all content and images on the site are contributed and maintained by our users.

- Go to the website and check the API documentation
- Create your API Key
- Test out the example to know what data to expect. **Note:** It is important to know what type of data you would expect and to prepare for it, because the API calls/requests are limited _(FREE accounts has 1000 requests daily limit)_
- To read a sample JSON format you can use this website : [CodeBeautify-JSON Viewer](https://codebeautify.org/jsonviewer)
- In python you can use:
  ```python
  from pprint import pprint
  pprint(json_data)
  ```

__Assigning our API Key__

In [63]:
API_KEY = '169932e1'   #--> Always keep it stored somewhere!

__Let's search for a movie:__ 

*Note:* the '**s=**' in the parameter refers to search *(refer to the documentation)*

In [70]:
# This is just to test the code and for out reference 
MOVIE_NAME = 'The Hobbit'                                                    #--> The movie name you want to search
url = f'http://www.omdbapi.com/?apikey={API_KEY}&s={MOVIE_NAME}&type=movie'  #--> URL to the API(Includes: API Key and Movie name. Notice the parameters)
omdb_sreq = requests.get(url)                                                 #--> Sending the Request with our modified URL
print(omdb_sreq.status_code)                                                  #--> Check request's response status code

200

In [71]:
omdb_data = omdb_sreq.json()                                                 #--> Gettoing the data in JSON format from the request's response
pprint(omdb_data)

{'Response': 'True',
 'Search': [{'Poster': 'https://m.media-amazon.com/images/M/MV5BMTcwNTE4MTUxMl5BMl5BanBnXkFtZTcwMDIyODM4OA@@._V1_QL75_UX380_CR0,0,380,562_.jpg',
             'Title': 'The Hobbit: An Unexpected Journey',
             'Type': 'movie',
             'Year': '2012',
             'imdbID': 'tt0903624'},
            {'Poster': 'https://m.media-amazon.com/images/M/MV5BMzU0NDY0NDEzNV5BMl5BanBnXkFtZTgwOTIxNDU1MDE@._V1_QL75_UY562_CR0,0,380,562_.jpg',
             'Title': 'The Hobbit: The Desolation of Smaug',
             'Type': 'movie',
             'Year': '2013',
             'imdbID': 'tt1170358'},
            {'Poster': 'https://m.media-amazon.com/images/M/MV5BMTYzNDE3OTQ3MF5BMl5BanBnXkFtZTgwODczMTg4MjE@._V1_QL75_UX380_CR0,1,380,562_.jpg',
             'Title': 'The Hobbit: The Battle of the Five Armies',
             'Type': 'movie',
             'Year': '2014',
             'imdbID': 'tt2310332'},
            {'Poster': 'https://m.media-amazon.com/images/M/MV5BYTJhODI1YjMtYjc0Ni00YTcyLTgxNjYtMzYzNDllZWI1ZTI0XkEyXkFqcGc@._V1_SX300.jpg',
             'Title': 'The Hobbit',
             'Type': 'movie',
             'Year': '1977',
             'imdbID': 'tt0077687'},
            {'Poster': 'https://m.media-amazon.com/images/M/MV5BOWIwNTQzYTQtNzNkOS00Zjc3LTliNTgtMTVlNjM4NTliNmM4XkEyXkFqcGc@._V1_QL75_UX380_CR0,1,380,562_.jpg',
             'Title': 'The Hobbit: The Battle of the Five Armies - Extended '
                      'Edition Scenes',
             'Type': 'movie',
             'Year': '2015',
             'imdbID': 'tt21832076'},
            {'Poster': 'https://m.media-amazon.com/images/M/MV5BZDg5MDcwZWYtYmRhNC00OWQ3LWI1MmYtMGQ3MjllOTBjMzhiXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
             'Title': 'The Hobbit: An Unexpected Journey - Extended Edition '
                      'Scenes',
             'Type': 'movie',
             'Year': '2013',
             'imdbID': 'tt21836008'},
            {'Poster': 'https://m.media-amazon.com/images/M/MV5BNTc3NjUxNzUtZTRlZC00YzAzLWI5NjItNDFkMzNjODc2ODg4XkEyXkFqcGdeQXVyMTA0MTM5NjI2._V1_SX300.jpg',
             'Title': 'The Hobbit',
             'Type': 'movie',
             'Year': '1966',
             'imdbID': 'tt1686804'},
            {'Poster': 'https://m.media-amazon.com/images/M/MV5BM2MwYWFmZmMtY2JhNy00N2VkLTgwZjUtMDhkOWRmMjY5OWY4XkEyXkFqcGdeQXVyMTEwNDU1MzEy._V1_SX300.jpg',
             'Title': 'The Hobbit: The Desolation of Smaug - Extended Edition '
                      'Scenes',
             'Type': 'movie',
             'Year': '2014',
             'imdbID': 'tt21824192'},
            {'Poster': 'https://m.media-amazon.com/images/M/MV5BMTk3ODI5Nzk4Nl5BMl5BanBnXkFtZTcwMDE5MTcyMQ@@._V1_SX300.jpg',
             'Title': 'A Day in the Life of a Hobbit',
             'Type': 'movie',
             'Year': '2002',
             'imdbID': 'tt0473467'},
            {'Poster': 'https://m.media-amazon.com/images/M/MV5BODEyZDM3MzktNzk4OS00ZDU2LTg3NzYtNjhhMzg2MDliN2U2XkEyXkFqcGc@._V1_SX300.jpg',
             'Title': 'The Hobbit: The Swedolation of Smaug',
             'Type': 'movie',
             'Year': '2014',
             'imdbID': 'tt4171362'}],
 'totalResults': '50'}

__Let's get more details:__

This time we will use '**t=**' instead to '**s=**' *(refer to the documentation)*

In [72]:
# This is just to test the code and for out reference 
MOVIE_NAME = 'The Hobbit'                                                    #--> The movie name you want to search
url = f'http://www.omdbapi.com/?apikey={API_KEY}&t={MOVIE_NAME}&type=movie'  #--> URL to the API(Includes: API Key and Movie name. Notice the parameters)
omdb_req = requests.get(url)                                                 #--> Sending the Request with our modified URL
print(omdb_req.status_code)                                                  #--> Check request's response status code

200

In [73]:
omdb_data = omdb_req.json()                                                 #--> Gettoing the data in JSON format from the request's response
pprint(omdb_data)

{'Actors': 'Orson Bean, John Huston, Theodore Gottlieb',
 'Awards': '1 win & 2 nominations total',
 'BoxOffice': 'N/A',
 'Country': 'United States, Japan',
 'DVD': 'N/A',
 'Director': 'Jules Bass, Arthur Rankin Jr.',
 'Genre': 'Animation, Adventure, Family',
 'Language': 'English',
 'Metascore': 'N/A',
 'Plot': 'A homebody hobbit in Middle Earth gets talked into joining a quest '
         'with a group of dwarves to recover their treasure from a dragon.',
 'Poster': 'https://m.media-amazon.com/images/M/MV5BYTJhODI1YjMtYjc0Ni00YTcyLTgxNjYtMzYzNDllZWI1ZTI0XkEyXkFqcGc@._V1_SX300.jpg',
 'Production': 'N/A',
 'Rated': 'TV-PG',
 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '6.7/10'},
             {'Source': 'Rotten Tomatoes', 'Value': '72%'}],
 'Released': '27 Nov 1977',
 'Response': 'True',
 'Runtime': '77 min',
 'Title': 'The Hobbit',
 'Type': 'movie',
 'Website': 'N/A',
 'Writer': 'J.R.R. Tolkien, Romeo Muller',
 'Year': '1977',
 'imdbID': 'tt0077687',
 'imdbRating': '6.7',
 'imdbVotes': '18,552'}

In [78]:
# Convert the data to DataFrame
df_movie = pd.DataFrame([omdb_data])
df_movie.head()

,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Plot,...,Metascore,imdbRating,imdbVotes,imdbID,Type,DVD,BoxOffice,Production,Website,Response
0,The Hobbit,1977,TV-PG,27 Nov 1977,77 min,"Animation, Adventure, Family","Jules Bass, Arthur Rankin Jr.","J.R.R. Tolkien, Romeo Muller","Orson Bean, John Huston, Theodore Gottlieb",A homebody hobbit in Middle Earth gets talked ...,...,N/A,6.7,"18,552",tt0077687,movie,N/A,N/A,N/A,N/A,True

In [79]:
# Let's explore the first record/observation
df_movie.iloc[0]

Title                                                The Hobbit
Year                                                       1977
Rated                                                     TV-PG
Released                                            27 Nov 1977
Runtime                                                  77 min
Genre                              Animation, Adventure, Family
Director                          Jules Bass, Arthur Rankin Jr.
Writer                             J.R.R. Tolkien, Romeo Muller
Actors               Orson Bean, John Huston, Theodore Gottlieb
Plot          A homebody hobbit in Middle Earth gets talked ...
Language                                                English
Country                                    United States, Japan
Awards                              1 win & 2 nominations total
Poster        https://m.media-amazon.com/images/M/MV5BYTJhOD...
Ratings       [{'Source': 'Internet Movie Database', 'Value'...
Metascore                                                   N/A
imdbRating                                                  6.7
imdbVotes                                                18,552
imdbID                                                tt0077687
Type                                                      movie
DVD                                                         N/A
BoxOffice                                                   N/A
Production                                                  N/A
Website                                                     N/A
Response                                                   True
Name: 0, dtype: object

__Notice__ the 'Ratings' column, it contains a list. This is something common you would face when dealing with some datasets, specially JSON formatted.

In [80]:
# Looking at the 'Ratings' value
df_movie.loc[0,'Ratings']

[{'Source': 'Internet Movie Database', 'Value': '6.7/10'},
 {'Source': 'Rotten Tomatoes', 'Value': '72%'}]

__Note :__ The columns Internet Movie Database, Rotten Tomatoes, and Metacritic and inside the Ratings column

Instead of having them all in a column, we can add each in a new column

In [81]:
# Create a new column 'Internet Movie Database' and add the rating
df_movie['Internet Movie Database'] = df_movie['Ratings'].iloc[0][0]['Value']
df_movie['Internet Movie Database'] = df_movie['Internet Movie Database'].str.split('/').str[0]
df_movie['Internet Movie Database'] = df_movie['Internet Movie Database'].astype(float)
df_movie['Internet Movie Database']

0    6.7
Name: Internet Movie Database, dtype: float64

In [82]:
# Create a new column 'Rotten Tomatoes' and add the rating
df_movie['Rotten Tomatoes'] = df_movie['Ratings'].iloc[0][1]['Value'] 
df_movie['Rotten Tomatoes']  = df_movie['Rotten Tomatoes'].str[0:-1]
df_movie['Rotten Tomatoes'] = df_movie['Rotten Tomatoes'].astype(float)
df_movie['Rotten Tomatoes']

0    72.0
Name: Rotten Tomatoes, dtype: float64

In [83]:
# We do not need this, because we already have a column
# df_movie['Metacritic'] = df_movie['Ratings'].iloc[0][2]['Value'] 
# df_movie['Metacritic'] = df_movie['Metacritic'].str.split('/').str[0]
# df_movie['Metacritic'] = df_movie['Metacritic'].astype(float)
# df_movie['Metacritic']

In [84]:
# Drop the Ratings column - We don't need it
df_movie = df_movie.drop(columns=['Ratings'])

# Select the columns 
df_movie

,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Plot,...,imdbVotes,imdbID,Type,DVD,BoxOffice,Production,Website,Response,Internet Movie Database,Rotten Tomatoes
0,The Hobbit,1977,TV-PG,27 Nov 1977,77 min,"Animation, Adventure, Family","Jules Bass, Arthur Rankin Jr.","J.R.R. Tolkien, Romeo Muller","Orson Bean, John Huston, Theodore Gottlieb",A homebody hobbit in Middle Earth gets talked ...,...,"18,552",tt0077687,movie,N/A,N/A,N/A,N/A,True,6.7,72.0

In [85]:
df_movie.iloc[0]

Title                                                             The Hobbit
Year                                                                    1977
Rated                                                                  TV-PG
Released                                                         27 Nov 1977
Runtime                                                               77 min
Genre                                           Animation, Adventure, Family
Director                                       Jules Bass, Arthur Rankin Jr.
Writer                                          J.R.R. Tolkien, Romeo Muller
Actors                            Orson Bean, John Huston, Theodore Gottlieb
Plot                       A homebody hobbit in Middle Earth gets talked ...
Language                                                             English
Country                                                 United States, Japan
Awards                                           1 win & 2 nominations total
Poster                     https://m.media-amazon.com/images/M/MV5BYTJhOD...
Metascore                                                                N/A
imdbRating                                                               6.7
imdbVotes                                                             18,552
imdbID                                                             tt0077687
Type                                                                   movie
DVD                                                                      N/A
BoxOffice                                                                N/A
Production                                                               N/A
Website                                                                  N/A
Response                                                                True
Internet Movie Database                                                  6.7
Rotten Tomatoes                                                         72.0
Name: 0, dtype: object

#### __Now it is your turn__
- Follow the example above and get the information for the following 10 movies. Using the '__t=__' parameter
- Apply what you have learned in the Python module to:
    - 🔁 To get the information for the 10 movies
    - 🐼 Convert them to a table
    - 💾 Save the cleaned data

In [91]:
# Our movie list (add more if  you want)
MOVIE_LIST = ['The Matrix','The Hobbit','Iron Man','Avengers']   #--> Enter the name of the movies (for now lets try out 10 movies)

#### Requesting the data:

In [96]:
# Requesting the data for each movie (10 times) and each time we add it to the list
movie_details = []
for movie in MOVIE_LIST:
    url = f'http://www.omdbapi.com/?apikey={API_KEY}&t={movie}&type=movie' 
    omdb_req = requests.get(url)
    movie_details.append(omdb_req.json())

In [102]:
# Create a DataFrame from the list of movies and display them
df_movies = pd.DataFrame(movie_details)
df_movies.head()

,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Plot,...,Metascore,imdbRating,imdbVotes,imdbID,Type,DVD,BoxOffice,Production,Website,Response
0,The Matrix,1999,R,31 Mar 1999,136 min,"Action, Sci-Fi","Lana Wachowski, Lilly Wachowski","Lilly Wachowski, Lana Wachowski","Keanu Reeves, Laurence Fishburne, Carrie-Anne ...",When a beautiful stranger leads computer hacke...,...,73,8.7,"2,243,093",tt0133093,movie,N/A,"$177,559,005",N/A,N/A,True
1,The Hobbit,1977,TV-PG,27 Nov 1977,77 min,"Animation, Adventure, Family","Jules Bass, Arthur Rankin Jr.","J.R.R. Tolkien, Romeo Muller","Orson Bean, John Huston, Theodore Gottlieb",A homebody hobbit in Middle Earth gets talked ...,...,N/A,6.7,"18,552",tt0077687,movie,N/A,N/A,N/A,N/A,True
2,Iron Man,2008,PG-13,02 May 2008,126 min,"Action, Adventure, Sci-Fi",Jon Favreau,"Mark Fergus, Hawk Ostby, Art Marcum","Robert Downey Jr., Gwyneth Paltrow, Terrence H...","After being held captive in an Afghan cave, bi...",...,79,7.9,"1,223,183",tt0371746,movie,N/A,"$319,034,126",N/A,N/A,True
3,The Avengers,2012,PG-13,04 May 2012,143 min,"Action, Sci-Fi",Joss Whedon,"Joss Whedon, Zak Penn","Robert Downey Jr., Chris Evans, Scarlett Johan...",Earth's mightiest heroes must come together an...,...,69,8.0,"1,555,308",tt0848228,movie,N/A,"$623,357,910",N/A,N/A,True

In [103]:
# Clean up the data and display the result
# Create a new column 'Internet Movie Database' and add the rating
df_movies['Internet Movie Database'] = df_movies['Ratings'].iloc[0][0]['Value']
df_movies['Internet Movie Database'] = df_movies['Internet Movie Database'].str.split('/').str[0]
df_movies['Internet Movie Database'] = df_movies['Internet Movie Database'].astype(float)
# Create a new column 'Rotten Tomatoes' and add the rating
df_movies['Rotten Tomatoes'] = df_movies['Ratings'].iloc[0][1]['Value'] 
df_movies['Rotten Tomatoes']  = df_movies['Rotten Tomatoes'].str[0:-1]
df_movies['Rotten Tomatoes'] = df_movies['Rotten Tomatoes'].astype(float)
# Remove the Ratings columns
df_movies= df_movies.drop(columns='Ratings')

In [104]:
df_movies.loc[0]

Title                                                             The Matrix
Year                                                                    1999
Rated                                                                      R
Released                                                         31 Mar 1999
Runtime                                                              136 min
Genre                                                         Action, Sci-Fi
Director                                     Lana Wachowski, Lilly Wachowski
Writer                                       Lilly Wachowski, Lana Wachowski
Actors                     Keanu Reeves, Laurence Fishburne, Carrie-Anne ...
Plot                       When a beautiful stranger leads computer hacke...
Language                                                             English
Country                                             United States, Australia
Awards                          Won 4 Oscars. 42 wins & 52 nominations total
Poster                     https://m.media-amazon.com/images/M/MV5BN2NmN2...
Metascore                                                                 73
imdbRating                                                               8.7
imdbVotes                                                          2,243,093
imdbID                                                             tt0133093
Type                                                                   movie
DVD                                                                      N/A
BoxOffice                                                       $177,559,005
Production                                                               N/A
Website                                                                  N/A
Response                                                                True
Internet Movie Database                                                  8.7
Rotten Tomatoes                                                         83.0
Name: 0, dtype: object

In [ ]:
# Save the cleaned data as csv
df_movies.to_csv('cleaned_movies')